// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Client struct {
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
	Name       string         `json:"name"`
	Email      string         `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Company    sql.NullString `json:"company"`
	Address    sql.NullString `json:"address"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	HourlyRate sql.NullString `json:"hourly_rate"`
	Currency   string         `json:"currency"`
}

type ExchangeRate struct {
	ID             int32        `json:"id"`
	BaseCurrency   string       `json:"base_currency"`
	TargetCurrency string       `json:"target_currency"`
	Rate           string       `json:"rate"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type Invoice struct {
	ID            int32          `json:"id"`
	UserID        int32          `json:"user_id"`
	ClientID      int32          `json:"client_id"`
	InvoiceNumber string         `json:"invoice_number"`
	IssueDate     time.Time      `json:"issue_date"`
	DueDate       time.Time      `json:"due_date"`
	Status        string         `json:"status"`
	Notes         sql.NullString `json:"notes"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type InvoiceTimeEntry struct {
	InvoiceID   int32 `json:"invoice_id"`
	TimeEntryID int32 `json:"time_entry_id"`
}

type TimeEntry struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	ClientID    int32          `json:"client_id"`
	Date        time.Time      `json:"date"`
	Hours       string         `json:"hours"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	HourlyRate  sql.NullString `json:"hourly_rate"`
}

type User struct {
	ID                        int32          `json:"id"`
	Email                     string         `json:"email"`
	PasswordHash              sql.NullString `json:"password_hash"`
	Name                      string         `json:"name"`
	CreatedAt                 sql.NullTime   `json:"created_at"`
	UpdatedAt                 sql.NullTime   `json:"updated_at"`
	OnboardingCompleted       sql.NullBool   `json:"onboarding_completed"`
	Plan                      sql.NullString `json:"plan"`
	PlanEndDate               sql.NullTime   `json:"plan_end_date"`
	Currency                  sql.NullString `json:"currency"`
	DateFormat                sql.NullString `json:"date_format"`
	TourCompleted             sql.NullBool   `json:"tour_completed"`
	EmailVerified             sql.NullBool   `json:"email_verified"`
	VerificationToken         sql.NullString `json:"verification_token"`
	VerificationTokenExpires  sql.NullTime   `json:"verification_token_expires"`
	PasswordResetToken        sql.NullString `json:"password_reset_token"`
	PasswordResetTokenExpires sql.NullTime   `json:"password_reset_token_expires"`
	GoogleID                  sql.NullString `json:"google_id"`
	OauthProvider             sql.NullString `json:"oauth_provider"`
	AvatarUrl                 sql.NullString `json:"avatar_url"`
	StripeCustomerID          sql.NullString `json:"stripe_customer_id"`
}
